[package]
name = "immune-system-simulator-20xx"
version = "0.1.0"
authors = ["Zoran Lazarevic <lazarevic.zoki91@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "*"